### ISSUE TITLE
Mapping "foo" to "my-plugin!foo" causes "Error: Error: Loader plugin did not call the load callback in the build" when building

### ISSUE THREAD

**Issue by javasplice** [requirejs/requirejs#1465]
If the map key and the argument passed to a loader plugin match, as in the case of `"foo": "my-plugin!foo"`, the optimizer will throw the following error:

```
Error: Error: Loader plugin did not call the load callback in the build:
my-plugin:
  my-plugin!foo
```

This error message seems strange. Ultimately, I expected this to work, or–if anything–that it would fail with a recursion problem. However, the error message doesn't sound like it was a recursion problem; it sounds more like it hung for some reason and the load timed out.

Now if _foo.js_ is moved into a directory called "foo" and the map changed to `"foo": "my-plugin!foo/foo"`, the optimizer throw the following error:

```
RangeError: Maximum call stack size exceeded
```

Okay, now that's a recursion error. In this case, it seems like the loader is stuck in an infinite loop, replacing the first "foo" in the path with "my-plugin!foo/foo".

So with that in mind, if we just move _foo.js_ into some directory that is not called "foo"–say, "bar"–and change the map to `"foo": "my-plugin!bar/foo"`, then it works.

My question is this: why does `"foo": "my-plugin!bar/foo"` work when `"foo": "my-plugin!foo"` does not?

**PS:** An example project is provided [here](https://github.com/jrburke/requirejs/files/71298/mapping-problem.zip) to showcase the scenarios detailed in this post. To build, run _build.sh_ with _build/_ as the current working directory. Maps for the 3 different cases are included in _webbap/main.js_; simply change which one is commented out to test.

**Comment by amenadiel** [comment]
When the parameter passed to the plugin is "bar/foo" then that path is converted in the `load` method. IIRC the lyfecicle is
- Is there a named define, path or map for "bar/foo"?
- If there isn't, then is there a path config for "bar"?
- If I there isn't, then is `./bar/foo.js` a valid path and there's a file in there?
- If there isn't, then  (╯°□°）╯︵ ┻━┻) 

In your example, in the first step, there is an explicit path or map definition for the parameter, so it translates recursively.

Depending on which plugin we are talking about, you coulld avoid this recursion by passing an explicit file extension `foo!foo.js`, an url `foo!http://www.mysite.com/foo.js` or a relative path `foo!./foo'.

**Comment by javasplice** [comment]
Thanks for the info! Your solution does indeed work for the example posted in which `foo.js` exists as a file in the project.

However, in our actual scenario, the module "foo" is contained in a bundle file that the project pulls in. In this case, there is not a `foo.js` file to which the config can point. Ultimately, we are attempting to map "foo" to "my-plugin!foo" so the fact that it was run through a plugin is transparent to application modules pulling in "foo".

Updated example in which "foo" and "my-plugin" have been moved into a bundle: 
https://github.com/jrburke/requirejs/files/77476/mapping-problem-bundle.zip.

**Comment by jrburke** [comment]
For the first case, with this config:

```javascript
    map: {
        "*": {
            "foo": "my-plugin!foo"
        }
    }
```

This is tricky, because resource IDs for loader plugin IDs (the "foo" part in "my-plugin!foo") go through name resolution, and the are resolved relative to the calling module ("bootstrapper" in this case). Part of name resolution is applying map config, so "foo" in relation to "boostrapper" matches the "*" config, and problems ensue.

I believe the "my-plugin!foo/foo" fails for a similar reason, "foo/foo" is resolved relative to "bootstrapper" and map config is config based on ID prefixes -- the first "foo" matches the "*" rule for "foo".

I do not think I can support that config given the importance of resolving resource IDs relative to the calling module, and not the loader plugin. The use of "my-plugin!bar/foo" works since the "bar" part does not have a config map entry, and that is likely what I suggest if that case needs to be support, place the my-plugin controlled resource under a different ID.

However, the second case where the original error case was about locating a module in a bundle, it sounds like that is a good case for [bundles config](http://requirejs.org/docs/api.html#config-bundles). It allows telling the loader 'if someone asks for "foo", load "bundle" to find it'.

Bundles config would be much more useful if the optimizer also helped to generate the bundles config. That is being tracked in requirejs/r.js#613. In the meantime, you could probably do a regexp scan for define('string', to build it up in your own post-build process.

Going to close given the ID resolution constraints. However, feel free to continue discussion here, particularly if I misunderstood part of the problem.

**Comment by Kraxxis** [comment]
Hey @jrburke, 

I'm hopping in as a colleague of @javasplice to hopefully give a better scenario of where this issue cropped up for us.

In our project we are trying to use plugins as a way to easily add behaviors onto different modules without having to modify a bunch of code throughout our project.  We are trying to do this while also pulling in prebuilt bundles into our project.

The issue described above encompass a problem we cant resolve without completely changing our pattern. Basically:

1. Foo is located in a pre built bundle we are referencing
2. Foo is referenced by modules both in the bundle and our project
3. We want to run Foo through our plugin such that these behaviors are applied when Foo is used and referenced in our project and the bundle

This falls apart due to the issue logged here; we can't remap "foo" to a "plugin'd" version of itself.  Can you offer us a path forward?

**Comment by jrburke** [comment]
What about: use the map config to point 'foo' for everyone to the 'foo-adapter' module, then in map config make sure that 'foo' for 'foo-adapter' is really 'foo'. Then foo-adapter can depend on 'foo', do its mods, then return the result, which to all other modules looks like 'foo'.

An example config with jquery and jquery-adapter is here, be sure to scroll down in the code sample to see it all:
http://jrburke.com/talks/moduleids/#/13
