### ISSUE TITLE
IE10 close after require jquery/tinyMCE

### ISSUE THREAD

**Issue by PetrBorisov** [requirejs/requirejs#1473]
IE10
if page have element with empty 'name' attribute
then after require jquery/tinyMCE  browser close with error
examples:
https://jsfiddle.net/psborisov/xc8eub9b/
https://jsfiddle.net/psborisov/4grfkvpr/

i try also few js libraries, all working good

**Comment by jrburke** [comment]
I haven't looked closely because I do not know the tinyMCE code and do not have IE10 immediately available to me, but if I were to guess, I expect that library may be trying to do a document.write() in this case, but that would be hazardous, would wipe out the page contents, since requirejs uses async loading. With async loading the library can finish after the DOM is available and a document.write() would then wipe out the page.

If that does not seem to be happening, then more info on what error is shown might help. It might take me a while to get IE10 up and running again.
