### ISSUE TITLE
Support for new Apple TV

### ISSUE THREAD

**Issue by jocke138** [requirejs/requirejs#1475]
We sat out to build an application for the new Apple TV using our RequireJS-based framework. Since the Apple TV doesn't provide a full browser, script loading failed. You can't use script tags nor web workers. However, Apple provide their own way of loading scripts with a global `evaluateScripts(scripts, callback)` function. 

An easy patch for that would be to add an `isAppleTV` boolean
```
isBrowser = !!(typeof window !== 'undefined' && typeof navigator !== 'undefined' && window.document),
isWebWorker = !isBrowser && typeof importScripts !== 'undefined',
isAppleTV = !isBrowser && !isWebWorker && typeof evaluateScripts !== 'undefined',
```

and then when loading the scripts, add a new else if
```
else if (isAppleTV) {
            evaluateScripts([url], function (success) {
                if (success) {
                    context.completeLoad(moduleName);
                } else {
                    context.onError(makeError('evaluateScripts',
                                    'evaluateScripts failed for ' +
                                        moduleName + ' at ' + url,
                                    e,
                                    [moduleName]));
                }
            });
        }
```

This may be slightly more than a two line fix, but I'll post it here anyway. If you prefer a pull request I can do that instead.

**Comment by jrburke** [comment]
Thanks for calling this out. My first impulse is to skip the isAppleTV variable and just do that check inline in the load function.

Also do you know if the evaluateScripts callback with the success, is that callback guaranteed to be fired right after the script is evaluated? I would expect so, but IE10 had an issue where the event for the load of the script did not fire right after the script evaluation, it could do a few evaluations before triggering the load callback, so I am a bit careful to watch out for that type of issue in new platforms.

**Comment by jocke138** [comment]
The documentation for that function seems to be non-existent, but still it's used in all apple's examples. We have also just made a small poc implementation so I can't really answer that question. 

There's a function called evaluateScript in javascriptcore, which might have something to do with it
([link to docs](https://developer.apple.com/library/ios/documentation/JavaScriptCore/Reference/JSContext_Ref/#//apple_ref/occ/instm/JSContext/evaluateScript:withSourceURL)) according to [this thread](https://forums.developer.apple.com/thread/19991) on apple forums

**Comment by jrburke** [comment]
Looks like this [globals doc](https://developer.apple.com/library/prerelease/tvos/documentation/TVMLJS/Reference/TVJSGlobalFunc_Ref/#//apple_ref/javascript/instm/Global/evaluateScripts) has some information, but it is fairly sparse, does not really address the question.

If you are set up to do a test, You could try loading about 10 script files, each with a separate call to evaluateScripts. In each file, put something like a console.log() or some logging call you will be able to see, at the start and end of the file, and then in each callback call for the evaluateScripts call. Also, be sure that some of the files in the middle of the list are bigger (like a few megabytes) followed by some small scripts that would be fast to load, to see if a slower to load file affects the faster ones.

If you would also like to prep a pull request let me know, if you would like the honor of doing the work. Otherwise, I can sort it out. Still not sure if I want to ship this yet, or maybe just officially document how a project that is running on the platform could override requirejs.load to add this kind of adapter.

**Comment by jrburke** [comment]
I have not gotten around to trying this myself, and I would like to wait to see if there is more of a need for this to be in core. For people that do want to run requirejs in an AppleTV environment, I think it should be enough to do the following:

1) Create a bootstrap.js file with the following contents:

```javascript
// Override requirejs.load to use evalScripts in apple tv mode.
requirejs.load = function (context, moduleName, url) {
  evaluateScripts([url], function (success) {
    if (success) {
      context.completeLoad(moduleName);
    } else {
      context.onError(makeError('evaluateScripts',
                      'evaluateScripts failed for ' +
                          moduleName + ' at ' + url,
                      e,
                      [moduleName]));
    }
  });
};

// You can then call requirejs methods if you want in here, or separate them
// out into a separate file.
requirejs.config({});
requirejs(['app']);
```

2) Then, load this script along with require.js:

```javascript
evaluateScripts(['require.js', 'bootstrap.js'], function (success) {});
```

I am going to tentatively close this issue for now, but people should feel free to comment here if there are issues with this approach, and we can reopen as needed.
