### ISSUE TITLE
Is it possible to implement a progress bar with require.js if it is limited to 1 file at a time?

### ISSUE THREAD

**Issue by JohnReedLOL** [requirejs/requirejs#1483]
Is it possible to limit require.js to upload one file at a time and then implement a progress bar showing what percentage of the total number of bytes have been uploaded for that one file?

I would like to use require.js for a simple video uploader.

Nevermind, there is a progress function

**Comment by jrburke** [comment]
You could override [requirejs.load](https://github.com/requirejs/requirejs/blob/b1f0dcc0e9a58a6ee1a1d7ed10e6a01756b447cf/require.js#L1877), since it gets notified of requests that want to go out over the network, but it may mean a good amount of wiring to get exactly what you want.

So not really a good way to get a granular count of files that are waiting to load. No plans to add anything for it either.

Closing as a discussion ticket, feel free to continue discussion here.
