### ISSUE TITLE
Support question - looking for optimal pattern for re-referencing deps

### ISSUE THREAD

**Issue by ORESoftware** [requirejs/requirejs#1509]
I created a hot-reloading system with RequireJS that works really, one drawback is the verbosity of having to re-specify the deps, for example:

```js
define([

        '+appState',
        '#allModels',
        '#allCollections',
        '#allFluxActions',
        'REACT_VIEWS_BASE/mapping-file-crud/children/choose-mapping-name',
        'REACT_VIEWS_BASE/mapping-file-crud/children/existing-mapping-list',
        'REACT_VIEWS_BASE/mapping-file-crud/children/select-filetype-dropdown',
        'REACT_VIEWS_BASE/mapping-file-crud/children/mapping-execute-action',
        'require',
        'module'
    ],

    function (appState, models, collections, allFluxActions, template, CMN, EML, SFD, MEA, require, module) {

        var FluxCartActions = allFluxActions['MappingTypeActions'];

        var initialState = {
            mappingName: null,
            fileType: null
        };

        var MappingCollection = collections['mapping-type'];

        var localModel = collections['local-collection'].findOrCreateLocalModel(_.extend({}, initialState, {
            moduleId: module.id
        }));


        var MappingTypeView = React.createClass(_.extend({

            getInitialState: function () {
                return localModel.toJSON();
            },

            componentDidMount: function () {
                this.listenTo(localModel, 'change', this.onLocalModelChange);
                this.listenTo(MappingCollection, 'add remove', this.onMappingCollectionChange);
            },

            onLocalModelChange: function () {
                this.setState(localModel.toJSON());
            },

            onMappingCollectionChange: function () {
                this.forceUpdate();
            },


            componentWillUnmount: function () {
                this.stopListening();
            },


            render: function () {

                EML = require('REACT_VIEWS_BASE/mapping-file-crud/children/existing-mapping-list');
                CMN = require('REACT_VIEWS_BASE/mapping-file-crud/children/choose-mapping-name');
                SFD = require('REACT_VIEWS_BASE/mapping-file-crud/children/select-filetype-dropdown');
                MEA = require('REACT_VIEWS_BASE/mapping-file-crud/children/mapping-execute-action');

//...etc
```

as you can see, in order for hot-reloading to work, I have to re-reference the React child-components in the render function of the parent React component. It works great as is, but the downside, as I said, is that I have to specify the full path again to all the child component deps. Is there some trick to avoid this somehow? Been thinking about this a lot, but am stumped. Thanks!

**Comment by ORESoftware** [comment]
I have at least one idea. If I establish a consistent relative path between the parent component and the child-components, then I can use some relative path trick with the module level require function. But I would still need those four lines in the render function...?

**Comment by ORESoftware** [comment]
What that would mean is the render function would become

```js

   render: function () {

                EML = require('./children/existing-mapping-list');
                CMN = require('./children/choose-mapping-name');
                SFD = require('./children/select-filetype-dropdown');
                MEA = require('./children/mapping-execute-action');

 ///...etc
```

is that right? Is there a better way perhaps?

**Comment by ORESoftware** [comment]
Unfortunately, with the explicit path problem, it looks like it prevents me from using an OOP style helper function

  render: function () {
        this.rereference(EML,CMN,CFD,MEA);

 ///...etc

unless somehow each child React component knew what its path was.

**Comment by jrburke** [comment]
I suggest using the [sugar syntax](http://requirejs.org/docs/whyamd.html#sugar) and then setting up a paths config for REACT_VIEWS_BASE/mapping-file-crud/children. If REACT_VIEWS_BASE is already a paths config, then replace it will the path that is from the baseUrl.

Also, asking for the require('') in the render() function does not change the behavior of the module tracing/loading: those dependencies will have already executed before the define factory function is called, since they were passed in as dependencies. Maybe it has an effect due to the hot reloading behavior, but if not, those can just be hoisted to the top of the factory function with the other require('') calls.

That would look something like this:

```javascript
// In the config section
requirejs.config({
  paths: {
    'mfc': 'path/to/mapping-file-crud/children'
  }
});

// later in the module
define(function(require) {
  var appState = require('+appState'),
    models = require('#allModels'),
    collections = require( '#allCollections'), 
    allFluxActions = require( '#allFluxActions');
    
  var MappingTypeView = React.createClass(_.extend({

    render: function () {
        var EML = require('mfc/existing-mapping-list'),
        CMN = require('mfc/choose-mapping-name'),
        SFD = require('mfc/select-filetype-dropdown'),
        MEA = require('mfc/mapping-execute-action');
    }
  }));
});
```

Closing as a discussion ticket, feel free to continue discussion here.

**Comment by ORESoftware** [comment]
Thanks, that might work. Good call ;)

Quick question, is it possible to mix and match?

Something like so, where some deps stilll remain in the dep array

```js
// later in the module
define(['+appState','#allModels'],function(appState, allModels, require) {
  
var collections = require( '#allCollections'), 
    allFluxActions = require( '#allFluxActions');

  var MappingTypeView = React.createClass(_.extend({

    render: function () {
        var EML = require('mfc/existing-mapping-list'),
        CMN = require('mfc/choose-mapping-name'),
        SFD = require('mfc/select-filetype-dropdown'),
        MEA = require('mfc/mapping-execute-action');
    }
  }));
});
```

**Comment by jrburke** [comment]
It is not possible to mix the explicit and sugared styles: the loader will only introspect the factory function for require('') calls if there is not a dependency array argument to the define() call.

As for minification, the r.js optimizer will scan the source and then inject all the dependencies as a dependency array so that it works after minification. If the build process does not use the r.js to do the minification, then you might want to set [normalizeDirDefines](https://github.com/requirejs/r.js/blob/98a9949480d68a781c8d6fc4ce0a07c16a2c8a2a/build/example.build.js#L115) to "all" to get this behavior.

**Comment by ORESoftware** [comment]
Ok thanks for the info, will see what I can do
