### ISSUE TITLE
After require.undef('some/thing'); require(['some/thing (the same)'], function(file){...}) get it from cash

### ISSUE THREAD

**Issue by Another84** [requirejs/requirejs#1510]
Hi there! Please help.
I thought that after require.undef() I can reload the same module from a sever. But require() still somehow managed to get it from cash.

What should I do?

Thank you.

P.S. I use "urlArgs: "bust=" + (new Date()).getTime(),"

**Comment by jrburke** [comment]
A more complete example, or more information, might help find the problem. For instance, if a module does this:

```javascript
define(['some/thing'], function(thing) {
  return function() {
    return thing;
  };
});
```

This modules `thing` reference will not be updated even if another module does the undef/require([]) steps, since the factory function is only called once and gets a local reference to the original definition.

Also, `"urlArgs: "bust=" + (new Date()).getTime(),"`, the urlArgs value is then set for the lifetime of loading to the same value (unless you call requirejs.config() again to set it to a new value). So if you were expecting the second require([]) load to use a new Date value, that will not happen automatically, the old value will be used, and then you will probably hit the browser cache and get the previous module value back.

If that is the issue, then the requirejs 2.2's support of an [urlArgs value that is a function](http://requirejs.org/docs/api.html#config-urlArgs) might be a way to solve it, to allow a different cache bust value on every call.

Going to close for now as I believe that is probably the issue, but feel free to continue the conversation with a more complete example or more information on how urlArgs is used, and we can reopen as needed.
