### ISSUE TITLE
Use “define()” to load a minified module file caused “ Failed to instantiate module”

### ISSUE THREAD

**Issue by needhelp62** [requirejs/requirejs#1516]
I asked this question at an earlier time and got some responses, but my problem is still not resolved. Now I would like to make my question to be a little more specific.

In my sys-config.js, I use define() to load my dependency module files. Without minification, everything works fine. But after I minified the module files, the code breaks with a message saying: “ Failed to instantiate module”. If I also minify sys-config.js into the same minified file, it works. However my project does not allow me to minified sys-config because it is a "configuration" file which should be modifiable easily. I post my code snippet below

My sys-config.js file is like this:
define([
     'modules/hello/main-min', // <-- minified, does not work
    // 'modules/hello/main'  // <-- unminified, works fine
], function onReady() {
     ...
    };
});

My minified module file (main-min.js) is like this:
define('myModule',['angular'], function (ng) {
     'use strict';
     var mod = ng.module('demo.hello', ['uaf.appshell']);
     mod.config(['$translatePartialLoaderProvider', function ($translatePartialLoaderProvider) {
         $translatePartialLoaderProvider.addPart('./modules/hello/i18n');
     }]);
    return mod;
});
define('controllers/hello-controller',[
    'angular'
], function (ng) {
    'use strict';
    var helloMod = ng.module('demo.hello');
    helloMod.controller('demo.hello.helloCtrl', ['$scope', function ($scope) {
        ...
    }]);
});
define('main',[
    './myModule',
    './controllers/hello-controller'
], function () {});

My question is: 
The main-min.js have multiple define() blocks with each one coming from different source file. When I load it from define() in another file sys-config.js, is it recognized as a requirejs module? Could it be loaded in this way? Could expert here help me to clarify this puzzle? Thanks!

**Comment by jrburke** [comment]
Before the r.js optimizer runs to concatenate the modules together, the main.js file likely just has `define(['./myModule'...` in it. In that scenario, since the module (correctly) does not name itself, it is anonymous, asking for `define(['modules/hello/main']...` works because the main module is anonymous, so it can use that 'modules/hello/main' name.

After bundling, then the module is inlined with the name 'main': `define('main', [....`. So, for the load to work, the other define has to be `define(['main']` for it to work. You can use paths config to map 'main' to 'modules/hello/main-min' in the after-build config to get it to work.

Closing as a discussion ticket.
