### ISSUE TITLE
[ bower/bootstrap-sass ] r.js: Failed by equal names for path and file

### ISSUE THREAD

**Issue by nimayneb** [requirejs/requirejs#1523]
Hi,

the problem with a bower installed "bootstrap-sass" is we have equal names for path and filename:
```text
- assets/javascripts/
  \- bootstrap/
  \- bootstrap.js
```

The content of config.js file:
```javascript
require.config({
	"paths": {
		"jquery"                : "../bower_components/jquery/dist/jquery",
		"bootstrap"             : "../bower_components/bootstrap-sass/assets/javascripts/bootstrap"
	},

	"wrapShim": true,

	"shim": {
		"jquery"                : { "exports": "$" },
		"bootstrap"             : { "deps" :["jquery"] }
	}
});
```

When i build this as module, we receive an error:
```error
{ [Error: ENOENT: no such file or directory, open 'C:\workspace\app\bootstrap.js']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\workspace\\app\\bootstrap.js',
  fileName: 'C:/workspace/app/bootstrap.js' }
Error: Error: Module loading did not complete for: bootstrap
    at Function.build.checkForErrors (C:\workspace\node_modules\requirejs\bin\r.js:31556:19)
```

Because we have the bootstrap folder in the app directory (build.json) now...

When i remove the "bootstrap" folder in "bower_components" everything builds OK.
When i change the name of the "bootstrap.js" to "bootstrap3.js" file and adopt this change in the config file everything builds as well.

How can i solve this problem?
I would like a change for the path mapping in config file: path mapping must have an ending slash. otherwise it is a file, or?

Greets

**Comment by jrburke** [comment]
I'm not sure I follow the problem. I set up a sample project using https://github.com/volojs/create-template as a base project template, renamed www/lib to www/bower_components, bower installed jquery and bootstrap-sass, and added the paths config and the other config above, and I can do a build with that.

Perhaps the key is this:

> Because we have the bootstrap folder in the app directory (build.json) now...

I am not sure what that means. Does this mean you also have an app/bootstrap.js as part of the project, that is not the bower components bootstrap, and you want to load that for the 'bootstrap' module ID, instead of the 'bootstrap' module ID to point to ../bower_components/bootstrap-sass/assets/javascripts/bootstrap?

**Comment by nimayneb** [comment]
I created an example:

[example.zip](https://github.com/requirejs/requirejs/files/208993/example.zip)

**Comment by jrburke** [comment]
If I do this change:

```patch
diff --git a/Require.json b/Require.json
index 835ca3e..dfcc1fc 100755
--- a/Require.json
+++ b/Require.json
@@ -1,5 +1,6 @@
 {
-  "baseDir": "./src_js",
+  "appDir": "./src_js",
+  "baseUrl": ".",
   "dir": "app/",
   "mainConfigFile": "src_js/Config.js",
 
```

it works. baseDir is not a supported build option, appDir + baseUrl are the way to configure [a whole project optimization](http://requirejs.org/docs/optimization.html#wholeproject).

Without passing it in, then the default value for appDir will be the current working directory, which is incorrect in this case.

Going to close as a config typo, but feel free to continue discussion here.
