### ISSUE TITLE
Protocol-relative URLs don't work in CommonJS modules.

### ISSUE THREAD

**Issue by iwareserictsai** [requirejs/requirejs#1539]
RequireJS can't load Protocol-relative URLs in CommonJS modules.

For example:
`define(function(require, exports, module) {`
`return require('//cdn.bootcss.com/require-css/0.1.8/css.min.js')`
`}`

I did some research and found out that all Protocol-relative URLs was ignored as comment.

**Comment by chrisknoll** [comment]
I thought require() calls accepted moduleIDs.  That path isn't a module ID is it?

**Comment by iwareserictsai** [comment]
Yes, require() calls can also accept urls, and the url will be module ID.`require('https://cdn.bootcss.com/require-css/0.1.8/css.min.js')` is OK. But if I change url to Protocol-relative URL(remove the leading "https:"), the module won't loaded without any error or warning.

**Comment by iwareserictsai** [comment]
Look at following lines around line 2083 in require.js version 2.2.0.

`callback`
`.toString()`
`.replace(commentRegExp, commentReplace)`
`.replace(cjsRequireRegExp, function (match, dep) {`
`deps.push(dep);`
`});`

Protocol-relative URLs just removed by `.replace(commentRegExp, commentReplace)` because "commentRegExp" is "`/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg`".

I think it can be improved.

**Comment by jrburke** [comment]
I will look at this for 2.2.1, but not sure how it will be resolved yet. The workaround is to use a [paths config](http://requirejs.org/docs/api.html#config-paths) to set up a module ID for that resource instead of using the URL directly. This will also allow more options when doing a build.

Related, #1538, but only because it is about the same regexp.

**Comment by jrburke** [comment]
This is addressed in #1582.
