### ISSUE TITLE
Optimizer not following `module` => `module/index` convention

### ISSUE THREAD

**Issue by jdthorpe** [requirejs/requirejs#1547]
Trying to convert a node module to an optimized AMD file fails like so: 

```bash
npm install deepcopy
r.js -convert node_modules/deepcopy/ deepcopy/
r.js -o baseUrl=deepcopy/ name=deepcopy paths.deepcopy=index out=deepcopy-bundle.js
#> Error: ENOENT: no such file or directory, open '/Users/me/deepcopy/lib.js'
```
As it turns out, `deepcopy/index.js` contains just one line: 
```JavaScript
module.exports = require('./lib');
```
`./lib` is a directory, and hence Node knows to import `./lib/index.js` but apparently the r.js optimizer does not. 

In this case, changing `baseUrl=deepcopy/` to `baseUrl=deepcopy/bin/`works fine, but this is not a generalizable solution, because the `node_modules/deepcopy/package.json` includes `main:"index.json"`, which refers to `deepcopy/index.js` and not `deepcopy/lib/index.js`.

I also read about [packages](http://requirejs.org/docs/api.html#packages) and found [this issue](https://github.com/requirejs/requirejs/issues/1190) and tried calling r.js this way:

```bash
r.js -o bundle.js
```
with this `bundle.js` file:
```JavaScript
// contents of bundle.js
({
	baseUrl: ".",
	name: "foo",
	out: "deepcopy-bundle.js",
	optimize: "none",
	packages:[
		{
		"name":"foo",
		"location":"deepcopy",
		"main":"index",
		}
	]
}
```
but the same error is generated as above...

**Comment by jrburke** [comment]
The commonjs conversion option just wraps the node module in a define() call and supports __filename and __dirname. However it does not support node's module ID resolution algorithm, like checking for "index.json, index.js", etc... since an AMD loader in a non-build case cannot do those multiple file lookups.

It is probably best to modify that require statement to point to the correct module ID via some step outside the r.js calls, no plans for the cjs convert call to try to mimic the node ID resolution algorithm given that non-build cases could not be supported.

Closing as a discussion ticket, but feel free to continue discussion here.
