### ISSUE TITLE
Mapping to an empty string

### ISSUE THREAD

**Issue by pimterry** [requirejs/requirejs#1551]
Is it intentional that creating a mapping to an empty string doesn't work? For example:

```javascript
requirejs.config({
    map: {
      test: {
        "lib": ""
      }
    },
});
```

This currently does nothing.

For various annoying reasons, I need to use different module ids in my tests when they refer to files in my codebase than the module ids used within the codebase itself. For example, in tests a module might be loaded as "lib/coord" and inside the codebase it would just be "coord". Both need to map to the same result (preferably just 'coord')

In principle this is just an id mapping problem, but the current mapping setting doesn't handle empty strings, so you can't map away segments. This comes from [this line](https://github.com/requirejs/requirejs/blob/master/require.js#L321), which checks whether a map value is truthy (which an empty string is not), instead of just checking if it's a string.

Is that intentional? Is there any obvious reason you wouldn't accept a quick PR to fix it?

**Comment by jrburke** [comment]
To restate to hopefully show that I am following: you could like to make it so that a module ID prefix could just be mapped to the top of the module ID space, so that if a particular module asked for "lib/coord", "lib/some/thing", they would result in using module ID "coord" and "some/thing" respectively.

That seems like a useful thing to have, and I would be open to a pull request for it.

**Comment by jrburke** [comment]
Closing per the discussion in #1552.
