### ISSUE TITLE
Require (require) doesn't work

### ISSUE THREAD

**Issue by audinue** [requirejs/requirejs#1576]
I love to write module in CommonJS syntax:

```javascript
define(function (require) {
  var stuff = require('./stuff')
})
```

However, in `require()` this syntax is not working:

```
require(function (require) {
  var stuff = require('./stuff')
})
```

**Comment by jrburke** [comment]
If defining a module, then define() should be used. If dynamically loading some modules, then the array form should be used in require: `require(['a', 'b'], function(a, b){});`

If you have a lot of modules that you want to dynamically load, you can use a named, define()'d module right above the require([]) call to trigger loading of that code:

```javascript
define('some-code', function(require) {
  var a = require('a');
  var b = require('b');
});

require(['some-code']);
```

There are no plans to support a `require(function(require) {}, function(){/*success callback*/}` form.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by audinue** [comment]
Thanks for replying.

However, I meant this syntax:

```javascript
require(function(require) { /* success callback */ })
```

Not:

```javascript
require(function(require) {}, function(){/* success callback */})
```

Also I will state my problem with the current implementation of RequireJS: Inconsistency.

Why `define(function(require){})` works but `require(function(require){})` doesn't?

I'm having a hard time answering this issue to my students.

Thanks again in advance :)

**Comment by jrburke** [comment]
Sorry I muddled my first response. Some more background:

`require()` as an async call in AMD loaders is just meant to dynamically load just a few modules. The idea is that if there are a lot of dependencies for a piece of code, it should probably just be its own define()'d module. 

Plus, since `require()` can be used in a dynamic code setting, it is more likely that the `require` name and interior arguments could be modified either by the user assigning `require` to some other variable, say `req`, then calling `req()`, or by the code passing through a minifier. 

This makes it hard to support the `function(require) { var a = require('a')})` format: For that to work, the loader uses Function.prototype.toString() to get the source string for that function, parse out the require calls, then load them before executing that function. But with the name changes, and with browsers not guaranteeing a reliable .toString() value makes this hazardous to do well reliably.

For `define(function(require) {})`, since define is a global function, it is not normally mangled, and so it is easier to allow for Function.prototype.toString() use. There are still hazards with it: it requires using an AMD module bundling tool, like r.js, to do the module bundling.

When looking ahead at how an ECMAScript compatible module loader API might look like, it is also of the opinion that these dynamic load calls will be for a very small set of modules. Currently I believe they only allow one module in the call, something like `loader.import(moduleId).then(function(module){})`.

So while it would be technically feasible to build a loader that could support `require(function(require){})`, the design of future APIs does not lead in that direction, the use cases do start to argue for just breaking that out into a separate module whose name is used in the dynamic require call, and there are more possibilities for the parsing to encounter issues that would lead to a runtime failure that would be difficult for the end user to debug.

**Comment by audinue** [comment]
If `require(function(require) {})` were implemented, users are prone to do something like...

```javascript
define(function (require) {
  var stuffPath = './path/to/stuff'
  require(function useStuff (require) {
    var stuff = require(stuffPath) // stuffPath here is undefined
                                   // because useStuff's body is evaluated at different scope.
  })
})
```

...which is hard to debug.

Very helpful.
Thanks for answering, James. :)
