### ISSUE TITLE
normalize() called twice for loader plugins (happens only when loaded for first time)

### ISSUE THREAD

**Issue by iimanii** [requirejs/requirejs#1577]
When a plugin module is first loaded with an appended resource (ie: `"Plugin!ResourceName"`), requirejs triggers the plugin.normalize() function twice in the process.

I'm not sure if this is intended or just a bug, but in order to avoid this I have to preload the plugin module first without resources (ie: `"require('plugin')`) then continue to use it elsewhere normally.

Basically these lines of code in requirejs are the ones in question (causes the normalize to be triggered twice)

``` javascript
943    callPlugin: function () {
                     ...
                    //If current map is not normalized, wait for that
                    //normalized name to load instead of continuing.
                    if (this.map.unnormalized) {
                        //Normalize the ID if the plugin allows it.
                        if (plugin.normalize) {
                            name = plugin.normalize(name, function (name) {
                                return normalize(name, parentName, true);
                            }) || '';
                        }

                        //prefix and name should already be normalized, no need
                        //for applying map config again either.
                        normalizedMap = makeModuleMap(map.prefix + '!' + name,
 975                                               this.map.parentMap);
```

makeModuleMap also calls normalize in the process (which is actually called with the already normalized name from previous call above)

**Comment by jrburke** [comment]
It would be good to have a test case that shows how this is causing a failure. 

The code is like it is to support encountering a module ID that uses a plugin, the plugin not being loaded, so the loader then loads the plugin, the reruns the normalization process to get the final normalized ID since loader plugins can participate in module ID normalization.

There could be an inefficiency there, but it should not cause a load failure. If it is, then it is likely either point to an initial configuration error, or assumption on the order of loading. There always could be a bug though, so if you have a test case, maybe put up in an github repo, that would help trace the issue.

I'm going to close this as a discussion ticket for now since this sort of issue is usually addressed just through conversation. However, it is really easy for us to reopen this issue if we have a test case that identifies a code change to do.

**Comment by iimanii** [comment]
Here is a simplistic example to illustrate the issue, the plugin `normalize` simply appends a `.xyz` to the name of the resource needed.

```
<html>
    <head>
        <script type="text/javascript" src="require.js"></script>        
    </head>
    <body>
        <script>
            function log(str) {
                var div = document.createElement('div');
                div.innerHTML = str;
                document.body.appendChild(div);
            }
            
            define('Plugin', function() {
                return {
                    /* requirejs plugin api functions */
                    load: function(name, parentRequire, onload, config) {
                        log('load: '+name);
                    },
                    normalize: function(name, normalize) {
                        log('normalize: '+name);
                        return name+'.xyz';
                    }
                }
            });
            
            require(['Plugin!hello', 'Plugin!world'], function(hello, world){
            
            });
        </script>
    </body>
</html>
```
The output shows that the first resource **`hello`** is passed into the **`load`** function as **`hello.xyz.xyz`**, this is because the **`normalize`** function is called twice on this resource. The second resource **`world`** doesn't suffer from this issue and is passed as **`world.xyz`**

Here is the output as shown in the browser
```
normalize: hello
normalize: hello.xyz
load: hello.xyz.xyz
normalize: world
load: world.xyz
```
