### ISSUE TITLE
Add disclaimer about `import` / `export` to home page!!

### ISSUE THREAD

**Issue by rozzzly** [requirejs/requirejs#1605]
So when I opened the projects home page (Ie: _[`requirejs.org`](https://requirejs.org)_ for the first time in quite a while, I felt someting was missing. What is that you ask? Well it's not that far away from 2017 and there is no mention of `es2015` `import`/`export` style module system. 

|  I'm NOT suggesting that there be some biting message condeming `requirejs` such as deprecated/pointless/obsolete/etc etc  | <img style="float:left;" src="https://cloud.githubusercontent.com/assets/2515134/19749546/65aae9e6-9baf-11e6-9730-0371b6a700bc.png" /> |
|----|----|

However, there really should be little disclaimer noting that now, **es2015 `import`/`export` is a the de-facto standard**. The message could look like: 
> Heads up! Modern JavaScript now supports `es2015-modules`; a standardized format using `import` / `export` tokens that builds on all the awesomeness of `requirejs`, `commonjs`, and `UMD` have brought to the web. [ We suggest you check it out ]!
>  
>  Don't worry, `requirejs` and friends are still really important! See how it is integral to `babel``/webpack`/etc not to mention that you can mix the two easily! [read more about it]

 [ Link to a few paragraphs on a seperate page]

------

it would be simple to add. I think its the right thing to do; `requirejs` is still an important player, but its' no longer my _go-to_ solution to the average project.

Idk, I see repos doing the same thing all the time. I think it's pretty reasonable, and **_responsible_**. Do you agree?

**Comment by jrburke** [comment]
I have a hard time suggesting import/export yet as they are primarily only usable via transpilers. There is no loader defined for them yet, and no dynamic capabilities set up for them yet.

I am very much looking forward to the day when ES has a complete module system, and I will be happy to point people to that system. However, that time is not yet. We are just seeing an early preview of the static form of module declaration that gets compiled down to some form that can actually be loaded. One of those forms, AMD modules, is something that requirejs can be used to load the modules.

Closing for now, but do look forward to doing this eventually.

**Comment by ScottFreeCode** [comment]
Given that `import`/`export` are in the standard but don't actually work in any browser (that I'm aware of) or Node, I'd say they're much more of a _de jure_ standard than a _de facto_ one, and that modern JavaScript *specifies* them but support depends more on tooling (transpilers, maybe clever bundlers).

I'd really like to see less encouragement of end developers to start using them and more discussion of why they're worth browsers' and Node's developers implementing. I mean, for instance, was there some advantage to using a Python-like keyword form that requires new syntax? I don't even know. I just know it's at least one reason that I have to keep pointing people back to Babel who hear that `import`/`export` are standardized now and figure therefore they should be preferred and can be expected to have been implemented wherever. (No, really -- I help maintain a test-runner library, and for some reason at least once a month somebody thinks that the reason `import` and `export` aren't working in their code is because the test runner doesn't support them. Yes, five seconds of running their code in Node directly would correct such confusion, but hey -- some folks really believe in TDD.) I'm sure there must be some rationale for inventing `import`/`export` instead of standardizing CommonJS (which at least has Node support) or AMD (which doesn't need host environment support, which is why I'm a huge fan and probably will be till Internet Explorer is forgotten no matter what else happens), but I'm also sure there's some rationale for why it's the one standardized feature Node hasn't bothered implementing even behind an experimental flag and browsers don't seem to have ever heard of (at least to go by compatibility tables); I'd really like to see less "everybody go use this new feature because it's nominally standardized" and more discussion of both those rationales so everyone knows what's at stake.

Then again, I also want transpilation to be a browser API instead of a tool step, so all the other languages get lifted up to JS's run-straight-from-the-filesystem convenience at the whim of anyone who can write the transpilation rules, rather than dragging JS down to their level of requiring a transpiler just to use it. So I suppose that counts as bias on my part.
