### ISSUE TITLE
Errors inside require success callback shouldn't trigger both local and global error handler

### ISSUE THREAD

**Issue by dgoldstein0** [requirejs/requirejs#1606]
```
requirejs.onError = function(err){
  console.log("global error handler");
}

require(["a"], function(a){
  throw new Error();
}, function(err) {
  console.log("local errback");
});
```

Expected: we see "local errback" printed to the console.
Actual: we see the global onError print "global error handler", then the errback fires printing "local errback"

I've managed to work around this for my code since both handlers get the same `err`, but figured at the least I'd document and report it for anyone else confused by this behavior.

**Comment by jrburke** [comment]
This is another example where the error pathways in requirejs are not optimal, one of the driving forces for redoing the internals, which is what [alameda](https://github.com/requirejs/alameda) tries to accomplish. 

Thanks for documenting the behavior, and for people that run across this in the future, the guidance is to try [alameda](https://github.com/requirejs/alameda) instead. It is what a 3.0 rework of requirejs would look like as far as cleaning up the internals. This issue is not likely to be fixed in the requirejs code, closing as an unfortunate shortcoming.
