### ISSUE TITLE
Domready run after image load complete

### ISSUE THREAD

**Issue by HULIANGA** [requirejs/requirejs#1608]
i have saw the issuse https://github.com/requirejs/requirejs/issues/875 and https://github.com/requirejs/requirejs/issues/463。
And i have seen that requirejs use document.readyState === "complete" to sign document ready.
But why not take the solution following below,which used in jquery
![image](https://cloud.githubusercontent.com/assets/4363954/20210469/be30020e-a834-11e6-929d-1090b02c56a4.png)

**Comment by jrburke** [comment]
requirejs itself no longer tries to detect DOM ready, there is a [domReady loader plugin](https://github.com/requirejs/domReady) instead. Any changes to that behavior would occur in that repo instead of here. The use of "interactive" has some tradeoffs, mentioned in the domReady code.

Closing as this repo does not detect dom ready any more.

**Comment by HULIANGA** [comment]
thx
