### ISSUE TITLE
module path does not exist

### ISSUE THREAD

**Issue by Legends** [requirejs/requirejs#1612]
i have project with three folders in the root:

tools: r.js, build.js
www: libs & modules
www-built: optimized files

Using the following build.js config:
```
{
    appDir:'../www',
    dir:'../www-built',
    mainConfigFile:'../www/assets/js/config.js',
```

I get a 

> module path does not exist

when I call `node tools/r.js -o tools/build.js` from the root folder in the command line.
It looks for a wrong path:
/www/www/assets/js/config.js

I don't know why r.js prepends the **www** folder to the path again, so I end up with a wrong path starting with www/www/...

If I add this path entry to my build.js file:

` config:'../../../assets/js/config'`

then i get this error:

![image](https://cloud.githubusercontent.com/assets/966368/20508283/bf06d3cc-b060-11e6-9203-33815e5f937e.png)

**Comment by jrburke** [comment]
It sounds like maybe the mainConfigFile is setting baseUrl. If you set the baseUrl explicitly in the build.js config, then I think that should fix the problem.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by Legends** [comment]
Are there any restrictions regarding the project structure? 
I have an MVC web application (VS2015) and I can get require.js to work using the "example-multipage".
I just have to change some paths in common.js, in order to make it work from my views.
But this then breaks the build file using r.js:

> C:\Users\User\Source\Repos\example-multipage\WebApplication1\WebApplication1>node tools/r.js -o tools/build.js
> 
> Tracing dependencies for: js/common
> 
> Tracing dependencies for: js/page1
> Error: ENOENT: no such file or directory, open 'C:\Users\User\Source\Repos\example-multipage\WebApplication1\WebApplication1\www-built\jquery.js'
> In module tree:
>     js/app/main1
> 
> Error: Error: ENOENT: no such file or directory, open 'C:\Users\User\Source\Repos\example-multipage\WebApplication1\WebApplication1\www-built\jquery.js'
> In module tree:
>     js/app/main1
> 
>     at Error (native)

**Comment by jrburke** [comment]
Taking a brief look at https://github.com/Legends/rjs/blob/master/WebApplication1/WebApplication1/tools/build.js it seems like the main issue is that the `include` entries are not module IDs but instead are something that look like paths. 

The entries in `include` should be the module IDs that are used in the app, and the root of the module ID space is usually the baseUrl, with paths config also considered.

So first suggestions are to remove the explicit `baseUrl` in the tools/build.js, and then for `include` use the module IDs instead of what looks like a path. For instance `include: ['jquery', 'app/lib']` and **not** include: `['../js/lib/jquery', '../js/app/lib']`.

A good rule of thumb is to match what the modules in your project use. For instance,  https://github.com/Legends/rjs/blob/master/WebApplication1/WebApplication1/www/js/app/main1.js uses 'jquery', so the `include` should also be `jquery`, as the r.js optimizer will be using those in-module dependency IDs to work out what modules to include in the built files.

**Comment by Legends** [comment]
James, thanks for taking time to explain!
But I have one general question regarding the project structure when using require.js.
As you know, ASP.NET MVC 5 has a different project structure then depicted in the require.js "[example-multipage](https://github.com/requirejs/example-multipage)"

When I copy the www and tools folder to the root of my MVC project and reference require.js in my view "Index.cshtml" like this:
`<script data-main="../www/js/page1" src="~/www/js/lib/require.js"></script>`

this does not work. Look at the network trace tab in chrome:
As you can see, page.js and common.js are resolved correctly, but main1.js does not.

![image](https://cloud.githubusercontent.com/assets/966368/20623273/15f30bf8-b307-11e6-8a49-8830c2306557.png)

Here is a [repository ](https://github.com/Legends/example-multipage-mvc-not-modified)where i've just copied the tools and www folder into the root of an MVC project and changed the Index.cshtml to reference require.js including "data-main" attribute, which replicates the above issue I have.
