### ISSUE TITLE
Using require.js logo

### ISSUE THREAD

**Issue by anacierdem** [requirejs/requirejs#1647]
Hi, couldn't find a better place to ask this. What is the licence for [logo](http://requirejs.org/i/logo.png) on the main site?

**Comment by Triloworld** [comment]
BSD or MIT licensed
Site, assets and this repo as signed by this license

**Comment by jrburke** [comment]
The logo is not stored in this repo, so not under BSD or MIT license. The logo, is part of the [requirejs-branding](https://github.com/requirejs/requirejs-branding) repo and subject to the license in that repo,

**Comment by Triloworld** [comment]
Consider change of footer, because MIT license is presented and other than author isn't. 
MIT license is in first place when someone will use logo. 
Like "Branding: (c) 2010 Andy Chung All Rights Reserved"
Thanks for clarifying :)
Is that logo can be used by third party? No license details, only author.
What are implication to have separately repo with other license?

**Comment by Triloworld** [comment]
Even more confusion with your blog: https://jrburke.com/2016/03/17/requirejs-2.2-alameda-1.0-released/
No actual data found about more changes of license

**Comment by jrburke** [comment]
I have updated the web site footer. That blog post was about the source code changing. Typically branding/logos do not follow open source licenses, they would be more copyright.

As far as use: as long as you are using the logo to represent requirejs, and not used to make a derivative or alternate logo for it or something else, or representing it as authored by anyone else other than Andy Chung, use is fine.

**Comment by Triloworld** [comment]
Thanks for claryfication

**Comment by jrburke** [comment]
Sorry forgot: if using it to sell something, you should contact Andy Chung directly.
