### ISSUE TITLE
require() doesn't work with async callbacks

### ISSUE THREAD

**Issue by nmain** [requirejs/requirejs#1694]
```
require(["foo"], async function(foo) {
    // ...
});
```

The callback will never be called because require.js doesn't think the callback is a function.

**Comment by chrisknoll** [comment]
So, looking at the documenation on async functions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function. The semantics are completely different. The return of an async is a promise.  The param of the require() call is a function to call back.  Making that async doesn't even make sense (who does it hand the resulting promise to to try to resolve?)  

Can you give the usecase where you'd pass an async as the callback?

**Comment by jrburke** [comment]
There are also no plans to support async functions in this way.

If you want an AMD loader that returns a Promise from a `require([])` call (so that you could do `await require(['a'])`), then [alameda supports that](https://github.com/requirejs/alameda#require-promise), but there are no plans to support it in requirejs.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by nmain** [comment]
Thanks for the quick reply.  My use case is simply for convenience:  If I want to use other things that return promises from within a require callback, then `async function` saves some typing:

```
require(["foo"], async function(foo) {
    // ... do some stuff with foo
    let bar = await fetch("bar");
    // ... do some stuff with foo and bar
});
```
In this case, I ignore the resolution of the `async function`; a page level `unhandledrejection` handler gives me as much error handling as I need.

Alameda seems to be a better fit for my use case though, so I'm OK with not changing this.
