### ISSUE TITLE
Throw when passing AsyncFunction to define()/require()

### ISSUE THREAD

**Issue by saschanaz** [requirejs/requirejs#1744]
Previous related discussion: https://github.com/requirejs/requirejs/pull/1729#issuecomment-382297882

[Just had a hard time](https://github.com/w3c/respec/pull/1767) debugging why `require([...], async () => {})` never executes the callback. It should at least throw with a descriptive error message so that users won't waste time to find the cause.

I would be happy if we can allow async functions for `require`, though.

**Comment by jrburke** [comment]
No plans to support async functions. [Trying to detect async functions is not recommended in this thread](https://github.com/tc39/ecmascript-asyncawait/issues/78).

And I can see if a transpiler like Babel is used, the transpiled code will not actually be an async function but something that returns a promise, which would be harder to detect as what case actually should be an error. The programmer could have just returned a promise out of habit, but actually handled the promise result inside the function passed to require, in a `.then().catch()` structure.

Closing as no plans to fix, since it would be hard to avoid false positives.

**Comment by saschanaz** [comment]
@jrburke 

>Trying to detect async functions is not recommended in this thread.

I absolutely agree with this statement, but we currently already [intentionally ignoring async functions](https://github.com/requirejs/requirejs/pull/1729#issuecomment-381836716). We should either do or do not differentiate async functions. Not in a mixed situation.
