### ISSUE TITLE
Security Vulnerability : eval() function

### ISSUE THREAD

**Issue by globeone** [requirejs/requirejs#1838]
According to Mozilla the eva() function should never be used as it's too much of a security risk. 

on line 2140 of require.js
a eva() function was inserted. 

Please see the page from Mozilla on alternatives to this eval() function. 

![image](https://user-images.githubusercontent.com/10052587/165296203-23bb39ba-f1f2-48b4-bcc3-0af80ed17f81.png)
 

"Warning: Executing JavaScript from a string is an enormous security risk. It is far too easy for a bad actor to run arbitrary code when you use eval(). See [Never use eval()!](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!), below."

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

**Comment by arunragha89** [comment]
Any update on the above security vulnerability?

**Comment by jrburke** [comment]
This is by design. That use of eval is only for loader plugins that operate without running through a build process via r.js. It is meant as a dev convenience only, and only for loader plugins. The core AMD module loading does not use eval, and production deployments should use a build process if loader plugins are involved.

No plans to change this. If you are concerned for your project, you can comment out or remove that line and as long as plain AMD modules are loaded or built modules are loaded, then it should not be needed.
