### ISSUE TITLE
UMD loading - global and AMD together?

### ISSUE THREAD

**Issue by AllanJard** [requirejs/requirejs#1842]
I'm the author of [DataTables](//datatables.net) and I recently [had a question](https://github.com/DataTables/DataTablesSrc/issues/213) about DataTables not working when Require JS is loaded and DataTables is invoked _not_ through `require`. I'm wondering what the authors / maintains of Require think is the correct thing to do in this situation.

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script>
$(document).ready(function () {
    $('#table').DataTable({});
});
</script>
```

Will fail due [to our UMD](https://github.com/DataTables/DataTablesSrc/blob/master/js/umd.js#L29) which will expose DataTables on the global scope only if it finds it is not either in an AMD or CommonJS environment. In the AMD case it registered itself as an AMD module and exits.

jQuery it appears is a little different. It will make itself available globally and then register an AMD module if in an AMD environment, allowing it to work. But then jQuery has its unique status in Require JS.

Would you expect scripts to be globally available as well as registering themselves as an AMD module?

**Comment by jrburke** [comment]
The options:

* load DataTables via a script tag before the require.is script tag. Looks like it would also be loading jquery before require.min.js 
* Load require.min.js then use require([]) to load both jquery and DataTables instead of using script tags. The idea being that if require.min.js is loaded in a page, then the assumption is that module loading via require/define are supposed to be used, particularly if the script supports UMD.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by AllanJard** [comment]
Excellent - many thanks for the confirmation!
