### ISSUE TITLE
Context sensitive define

### ISSUE THREAD

**Issue by it-ony** [requirejs/requirejs#237]
I like the multiversion support of requirejs, but the context sensitive define is missing.

I tried to get some object defined in the correct context but without success.

```
var req = requirejs.config({context: "foo"});

req(["require"], function(r){
// r is a require function in the context named "foo"
define("bar", "my value or object");
});

// at a later point
req(["bar"], function (bar) {
// error thrown because bar.js or node module bar cannot be found
// this is because the define is made on the global context
});

```

I didn't found any way to define something in the context. The following would be nice.

```
var req = requirejs.config({context: "foo"});
req(["require", "define"], function (r, d) {
// r - context sensitve require
// d - context sensitve define
});

```

If there is any other solution to solve this problem, please let me know.
Tony

**Comment by usagene** [comment]
So I recently ran into a similar problem with contextual require calls. The solution @roberttod mentioned works in simple case, in complex cases like below, it becomes a little tricky with various timing issues.

The example assumes we have one html file defines 3 script tags, first one points to bundle1.js, 2nd one points to moduleC.js, 3rd one contains the require calls. 

Files:
bundle1.js: contains two modules
define("moduleA", function(){...});
define("moduleB", function(){...});

moduleC.js: defines module C alone
define("moduleC", function(){...})

----------------------- Content for the 3rd script tag----------------
// global require to moduleC
require(["moduleC"], function(){
      // This call would claim moduleA, moduleB and moduleC to the default context "_" and clear the global define queue.
...
});
// Now setup contextual instance and require modules in bundle1.js
var bundle1Context = require.config({context: "bundle1"});

// This actually results in 404 because RequireJS tries to resolve the dependency by looking for moduleA.js. And since moduleA is bundled in bundle1.js, there is no such file.
bundle1Context(["moduleA"], function(){...})


With @roberttod solution, I pretty much needs to reload the bundle again, which kind defeats the purpose of bundle. Any thoughts on how to approach this?

**Comment by maxgrass** [comment]
This must be documented, I wasted multiple debug hours on that, as no errors get reported when the context uses other modules "claimed" by another context.

**Comment by priteshacharya** [comment]
How to use the simplified define wrapper with context specific require
I have 
```
define(function (require) {
    var namedModule = requireWithContext('name');
});
```
But it's failing with 
> "Module name has not been loaded yet for context"

**Comment by jrburke** [comment]
@priteshacharya: inside a define() function, the local require should always be used, the context stuff is for the globally visible variables. So it should be enough to do:

```javascript
define(function (require) {
    var namedModule = require('name');
});
```

and if that module is loaded by the correct context it should work out.
