### ISSUE TITLE
RequireJS 2.0 fallback doesn't work for folders.

### ISSUE THREAD

**Issue by AsaAyers** [requirejs/requirejs#348]
```
 require.config({
   baseUrl: '/js',
   paths: {
     'modules': [ 'optimized', 'modules' ],
     'modules/foo': [ 'optimized/foo', 'modules/foo' ]
   }
 })
```

With this configuration I can require 'modules/foo' and for my development environment where I don't have an optimized (with r.js) version of foo.js it will fall back to my unoptimized version in /js/modules/foo.js.

If I require 'modules/bar' it will only try /js/optimized/bar.js never falling back to /js/modules/bar.js.

**Comment by chrisknoll** [comment]
@jrburke : I'm commenting here because I didn't want to open up a new issue that is facing a similar issue:

I'm currently installing fallbacks in one of my apps that use requireJS because some of the environments that we are going to be deploying our webapp need to run in a 'disconnected' mode (they do not have access to the public internet) and therefore can not access CDNs on the internet.  This is what my config looks like:

~~~~javascript
requirejs.config({
	baseUrl: "js",
	packages: [
		{
			name: "databindings",
			location: "//rawgit.com/OHDSI/Circe/master/js/modules/databindings"
		}
	],	
	config: {
		text: {
			useXhr: function (url, protocol, hostname, port) {
				return true;
			}
		}
	},
	paths: {
		// application configuration
		"appConfig" : "config",
		// 3rd party libs
		"jquery": ["http://cdn.rawgit.com/jquery/jquery/1.11.2/dist/jquery.min","jquery-1.11.1.min"],
		"jquery-ui": "jqueryui/jquery-ui.min",
		"d3": ["http://cdn.rawgit.com/mbostock/d3/v3.5.5/d3.min", "d3-3.5.5.min"]
		"knockout": ["http://cdn.rawgit.com/knockout/knockout/v3.3.0/dist/knockout","knockout-3.3.0"],
		"director": "director.1.2.6.min",
		"databindings/knockout.selectOnFocus": "http://cdn.rawgit.com/One-com/knockout-select-on-focus/v0.1.5/lib/knockout.selectOnFocus",
		// OHDSI components
		"cohortbuilder": "http://rawgit.com/OHDSI/Circe/master/js/modules/cohortbuilder",
		"conceptsetbuilder": "http://rawgit.com/OHDSI/Circe/master/js/modules/conceptsetbuilder",
		"feasibilitystudy": "modules/feasibilitystudy",
		"webapi" : "modules/WebAPIProvider",
		"datatables": "jqueryui/jquery.dataTables.min",
		"vocabularyprovider": "modules/WebAPIProvider/VocabularyProvider",
		// plugins
		"text": "requirejs/plugins/text",
		"css": "requirejs/plugins/css",
		"json": "requirejs/plugins/json",
		"ColVis": "jqueryui/dataTables.colVis.min"
	},
	shim: { 
		"director": { exports: "Router" } 
	},
	deps: ['jquery',
				 'jquery-ui',
				 'jqueryui/jquery.ui.autocomplete.scroll',
				 'css!jqueryui/jquery.dataTables.css',
				 'css!jqueryui/dataTables.colVis.css'
				]
});
~~~~

Some of these fallbacks are incomplete, but you can see what i'm doing for Jquery, Knockout and D3.

Now at the top, I have declared a package, put the location to a CDN. This WORKS! It pulls the /.main.js file to load the package up, all is well, But if I change it to the following:

~~~ javascript
	packages: [
		{
			name: "databindings",
			location: ["//rawgit.com/OHDSI/Circe/master/js/modules/databindings", "databindings"]
		}
	],	
~~~

It does not work. I was hoping that it would attempt to load the main.js file from the CDN, failing that, resolve it to just the module "databindings/main".

I'm hoping your answer is not going to be to just make a module called databindings/main because there's already a lot of application code out there that do things like:

~~~ javascript
define(['knockout', '../siblingModule', 'databindings'], function (ko, otherModule) { ... });
~~~

And going through all those 'databindings' references and changing them up to databindings/main would HURT.  Any suggestions?

-Chris

**Comment by chrisknoll** [comment]
I should add: in order to test the CDN fallback, I just change the CDN path to a bogus URL so that it attempts to load it from the fallback position.

**Comment by jrburke** [comment]
@chrisknoll that sounds like wanting fallback support for packages config, which is better tracked as a separate issue. It definitely will not work today though to use an array for a packages location config.
