### ISSUE TITLE
Possible to optimize the template files?

### ISSUE THREAD

**Issue by sk29110** [requirejs/requirejs#443]
My backbone + required.js has grown over 6 month now I have more than 30 templates so first time user access the page It takes some time to load all files. Is there any way to resolve this? maybe r.js to minify?

**Comment by ORESoftware** [comment]
this is cool

**Comment by chrisknoll** [comment]
I'd just like to say, that's just amazing.

**Comment by ORESoftware** [comment]
I got it working, but only in so far as I have 2 optimized files, it would be great to be able to put it into just one file, but right now I do this:

in layout.html
```
    <script src="/static/vendor/require.js"></script>
    <script src="/static/app/js/optimized_templates.js"></script>
    <script src="/static/app/js/optimized.js"></script>
```

in build.templates.js  (just optimizes all the templates):

```javascript
({
    "optimizeAllPluginResources": true,
    "baseUrl": "./public/static",
    "name": "app/js/allTemplates",
    "mainConfigFile": "./public/static/app/js/main.js",
    "out": "./public/static/app/js/optimized_templates.js",
})
```

in build.js

```javascript
({
    "baseUrl": "./public/static",
    "name": "app/js/main",
    "mainConfigFile": "./public/static/app/js/main.js",
    "out": "./public/static/app/js/optimized.js"
})
```

allTemplates:

```javascript
define(
    [
        'text!app/templates/homeTemplate.ejs',
        'text!app/templates/header.ejs',
        'text!app/templates/footer.ejs'
    ],

    function (HomeTemplate,HeaderTemplate,FooterTemplate) {

        return {
            HomeTemplate: HomeTemplate,
            HeaderTemplate: HeaderTemplate,
            FooterTemplate: FooterTemplate
        };
    });
```

(by the way Mr. Burke, r.js / RequireJS is a very impressive software system - I discovered something so astounding that it almost makes me doubt it was intentional!). Here it is:

```javascript
define(
    [
        'app/js/models',
        'form2js',
        'ejs',
        'jquery',
        'underscore',
        'handlebars',
        'backbone',
        'backbone-validation',
        'text!app/templates/header.ejs'
    ],


    function (models, form2js, EJS, $, _, Handlebars, Backbone, BackboneValidation,template) {
```

...the amazing thing is that if I am in development,  'text!app/templates/header.ejs' refers to the actual file in that directory. But if I am in production, and have imported the optimized_templates.js file, then 'text!app/templates/header.ejs' refers to the module inside the optimized_templates.js file. Thus my JS code needs absolutely no conditionals. If this were planned, this was seriously absolute GENIUS.

Here is my main.js file:

```javascript
requirejs.config({
    enforceDefine: false,
    waitSeconds: 8,
    baseUrl: '/static',
    paths: {
        'async': 'vendor/async',
        'jquery': 'vendor/jquery',
        'ejs': 'vendor/ejs',
        'text': 'vendor/text',
        'form2js': 'vendor/form2js',
        'underscore': 'vendor/underscore',
        'ijson':'vendor/idempotent-json',
        'backbone': 'vendor/backbone',
        'bootstrap': 'vendor/bootstrap',
        'handlebars': 'vendor/handlebars',
        'backbone-validation': 'vendor/backbone-validation-amd',
        'socketio':'vendor/socketio'
    },

    'shim': {
        'homeTemplate':{
            'deps': ['text']
        },
        'underscore': {
            'exports': '_'
        },
        'backbone': {
            'deps': ['jquery', 'underscore'],
            'exports': 'Backbone'
        },
        'handlebars': {
            'exports': 'Handlebars'
        },
        ejs: {
            exports: "ejs"
        }
    }
});

require(['app/js/app'], function (Application) {
        var app = Application.start();//
});
```
The three "problems" I am having:

(1) for some reason I have to use  "name": "app/js/main", for the build.js file, but I would actually expect to be using "name": "app/js/app" ( as in require(['app/js/app']) (see above) instead.

(2) Like I said, I haven't been able to figure out how to put everything in one file, right now I only have it working with two separate files (optimized.js and optimized_templates.js). This might even be better to keep the templates separated from the code.

(3) r.js doesn't bundle all the files I need, only the ones specified in app/js/main.js, is there a way to have r.js bundle the dependencies from more than one module into one file?
