### ISSUE TITLE
Map config with a plugin value does not work

### ISSUE THREAD

**Issue by jrburke** [requirejs/requirejs#466]
``` javascript
requirejs.config({
  map: {
    '*': {
      'jquery': 'dollar!'
    }
  }
});
```

Ends up with a request for `dollar!.js`.

It looks like makeModuleMap does not check for a normalize() value that gives back plugin ID.

**Comment by dcleao** [comment]
I don't get it :-(
I'm using the latest requirejs version (2.1.17) and I can't get this to work...

```javascript
require.config({
    baseUrl: "/base",
    paths: {
        "bar": "Barrr/bar"
    },
    map: {
        "*": {
            "foo": "bar!gugu"
        }
    }
})
```

Calling `require.toUrl("foo")` is returning `"/base/bar!gugu"` instead of something like `"/base/Barr/bar!gugu"`

Even if the meaning of plugin module ids is not totally defined for `require.toUrl`,
I'd however expect that requiring `"foo"` would work, however, it tries to fetch the file "/base/Barr/bar!gugu.js"...

Am I doing something wrong? Any help is appreciated. Thanks.
