### ISSUE TITLE
module require.toUrl relative paths

### ISSUE THREAD

**Issue by guybedford** [requirejs/requirejs#515]
Following up on the Group discussion - 

This is one of those things where I may be doing something really stupid in my test environment, so my apologies if this turns out to be incorrect.

Basically I write a module called 'test/module', which contains:

``` javascript
define(['require'], function(req) {
  console.log(req.toUrl('./test'));
  console.log(require.toUrl('./test'));
  req(['./test'], function(){}, function(){});
  require(['./test'], function(){}, function(){});
});
```

The console output I get is (running on my local fileserver):

```
  lib/./test
  lib/./test 
  GET file://localhost/Users/guybedford/Projects/Test/www/lib/test/test.js
  GET file://localhost/Users/guybedford/Projects/Test/www/lib/test.js
```

**Comment by jslegers** [comment]
Suppose I have an folder `/tests/resources/` and a module named `tests/view/feature/PlotPixelTest`, located at  `/tests/view/feature/PlotPixelTest.js`.

I would espect to get the url of folder `tests/resources/` from module `tests/view/feature/PlotPixelTest` by calling `require.toUrl("../../../resources/")`.

The Dojo loader gives me the expected result. RequireJS gives me `/tests/view./resources/`, which is not correct.

Is this the expected behavior? And if yes, what is the recommended workaround?

**Comment by jslegers** [comment]
I've done some further digging and came to discover my issue was caused by `require.toUrl` determining the position of the extension by taking the last dot of a path and considering everything starting from that dot as an extension.

This is very annoying, especially because this makes the behavior of `require.toUrl` different for RequireJS and the Dojo loader and results in invalid paths in RequireJS for even paths as simple and common as `../resources/`.

This could easily be fixed by determining the position of the extension with a regex, which should make `toUrl` much more flexible while having a minimal impact on performance.

See https://github.com/requirejs/requirejs/pull/1779 for a proposed change to the source code.
