### ISSUE TITLE
enforceDefine incompatible with exports and init

### ISSUE THREAD

**Issue by honzajde** [requirejs/requirejs#680]
This issue is related to https://github.com/jrburke/requirejs/issues/420. I am usign requirejs with angular and I am loading angular moduels, e.g ui module and want to use enforceDefine. 
Angular modules dont export any value. From the point of enforceDfine I need to check angular.module('ui') is not null. init function defined as 

```
       init : function(angular){
            return angular.module('ui');
        }
```

does not override exports output, e.g. exports : 'true' fails on No define call for angular-ui. 
If I want to be 'sure' in IE that the script loaded I need to check for enforceDefine, right? 

Documentation needs to be more clear on the relationship of exports and init. At least for myself.

Thanks for this great lib!

.

**Comment by Jamby93** [comment]
@jrburke 
How can we use enforceDefine with a module that adds function/objects to a required dependency (still not correctly defining a module)?
Such example is [moment-duration-format](https://github.com/jsmreese/moment-duration-format) which adds `moment.duration.fn.format` to "required" moment (see [L189](https://github.com/jsmreese/moment-duration-format/blob/master/lib/moment-duration-format.js#L189)) but does not expose anything on global.
We can define the shim configuration like this:
`"moment-duration-format": {
			deps: ["moment"],
			init: function (moment) {
				return moment.duration.fn.format;
			}
		},`
But that will break with enforceDefine: true. The only way we managed right now is to define a fake exports string which we know exists in the global context (like `alert`) in order to let enforceDefine check pass and call the init function which in turns change the exported value to the correct one. 
Besides looking messy, I guess it simply bypass the check that should fire an error if the expected exported is not present/hasn't been initialized correctly.
