### ISSUE TITLE
Add minified version of require.js for Bower support

### ISSUE THREAD

**Issue by rodikal** [requirejs/requirejs#737]
Can you add the minified version of require.js (as available on http://requirejs.org/docs/download.html ) to allow installing it via Bower (http://bower.io)

**Comment by NgYueHong** [comment]
I think it's best to include minified version of RequireJS and let developer to decide how they want to use it.

**Comment by PavelKonon** [comment]
I completely agree that developers can have reasons to use minified version. Please add it to repository.

**Comment by jgomo3** [comment]
Or simply tell us exactly how you produce the minified version given in the download page. Then we developers could replicate those steps in our build process.

**Comment by jrburke** [comment]
The one on the download site is generated by running it through an older version of closure compiler, but any modern minifier should be fine to use.

**Comment by jgomo3** [comment]
Cool. Thank you. That is enough for me.

**Comment by surma** [comment]
I would like to make yet another case for including a minified version. Sorry for reviving this, but I’d like to see if you can see my point.

HTTP/2 is coming and concatenation of source files will become less prominent; not only because it’s unnecessary (requests are cheap and no HOL blocking) but because concatenation makes client-side caching much more inefficient (small change :arrow_right: big download) and usually causes you to download code that will not be run. Consider RequireJS with something like BabelJS to use ES2015 modules today. Running `requirejs-optimizer`, or any similar tool, will probably get phased out from building pipelines like `gulp`. 

Minification, however, is still an important step. Having to know which files in `bower_components` to minify and which to skip to optimize build times is quite annoying and complicates the setup. I’d like to ask you to follow the common pattern to include both files in your bower package: The commented source and a minified version. :star:

**Comment by tammyalexandra** [comment]
+1
