### ISSUE TITLE
jQuery example using noconflict may fail

### ISSUE THREAD

**Issue by Tug** [requirejs/requirejs#978]
The example here http://requirejs.org/docs/jquery.html#noconflictmap
will not work if some other script access `window.jQuery` before `jquery-private` is loaded.
This is made possible due to the `jquery-private` module being loaded asynchronously.

`jQuery.noConflict( true );` needs to be called synchronously after jQuery's definition.

Is there a special config option in requirejs to achieve this ?

**Comment by Blasz** [comment]
@jrburke There will always be a 4 ms window regardless of the existence of dynamically loaded modules due to the `req.nextTick` function.

What worked for me when having a built file containing both jquery and jquery-private was to define jquery-private like so:

```
(function() {
    var jqp = jQuery.noConflict(true);
    define(['jquery'], function (jq) {
        if(jqp !== jq) {
            console != null ? console.error("jquery-private noConflicted wrong version of jQuery") : "";
        }
        return jq;
    });
})();
```

The jquery module should be placed earlier in the built file than jquery-private and therefore the noConflict should always occur on the built file's version of jQuery so the error checking is probably not needed.

Perhaps the documentation should be updated with this version for the case where they are both in a built/optimized file.

**Comment by Blasz** [comment]
The map configuration is also not needed after putting the noConflict outside the define.
